spring.application.name=Staylio Backend
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/staylio_db
spring.datasource.username=root
spring.datasource.password=me@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Logging configuration
logging.level.org.springframework.web.cors=DEBUG
logging.level.com.staylio.backend=DEBUG